kind = "DojoModel"
class_hash = "0x71e191e88aad0d5eb241e27c375cd532928e055a9e7787abf6bbe61c6c062d"
original_class_hash = "0x71e191e88aad0d5eb241e27c375cd532928e055a9e7787abf6bbe61c6c062d"
abi = "manifests/dev/base/abis/models/diamond_pit-PlayerPosition-69b522e7.json"
tag = "diamond_pit-PlayerPosition"
qualified_path = "diamond_pit::models::player_position::player_position"
manifest_name = "diamond_pit-PlayerPosition-69b522e7"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "z"
type = "u32"
key = false

[[members]]
name = "time"
type = "u64"
key = false
