kind = "DojoModel"
class_hash = "0x4f2c42a85652e649f70de3221600c24a4e68df8a59b98a9e7cf11b2833e3b3d"
original_class_hash = "0x4f2c42a85652e649f70de3221600c24a4e68df8a59b98a9e7cf11b2833e3b3d"
abi = "manifests/dev/base/abis/models/diamond_pit-PlayerInventory-676ae3a3.json"
tag = "diamond_pit-PlayerInventory"
qualified_path = "diamond_pit::models::player_inventory::player_inventory"
manifest_name = "diamond_pit-PlayerInventory-676ae3a3"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "data"
type = "u64"
key = false

[[members]]
name = "coins"
type = "u64"
key = false

[[members]]
name = "rebirth_credits"
type = "u64"
key = false
